package com.evolution.analysis.spring.condition;

import com.evolution.analysis.contract.common.*;
import com.evolution.analysis.contract.serialization.CanonicalJson;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ConditionExpressionTest {
    static final ConditionExpression.Semantics SEMANTICS = new ConditionExpression.Semantics(
            new VersionedIdentifier("spring.fixture-semantics", "r0-v1"), ContentDigest.sha256Utf8("pinned-fixture"));

    static ConditionExpression profile(String name) {
        return ConditionExpression.atom(SEMANTICS, new ConditionExpression.Profile(name));
    }

    @Test void pureCommutativeContentIsCanonicalButStatefulOrderIsPreserved() {
        var a = profile("a"); var b = profile("b");
        assertEquals(ConditionExpression.all(SEMANTICS, List.of(a, b)).identity(),
                ConditionExpression.all(SEMANTICS, List.of(b, a)).identity());
        var opaque = ConditionExpression.atom(SEMANTICS, new ConditionExpression.Opaque(
                ContentDigest.sha256Utf8("custom-condition"), ConditionExpression.OpaqueReason.CUSTOM_CODE));
        assertNotEquals(ConditionExpression.all(SEMANTICS, List.of(a, opaque)).identity(),
                ConditionExpression.all(SEMANTICS, List.of(opaque, a)).identity());
        assertThrows(IllegalArgumentException.class, () -> ConditionExpression.all(SEMANTICS, List.of(a, a)));
    }

    @Test void unknownDoesNotObeyExcludedMiddleAndAllKleeneTablesAreClosed() {
        LogicalValue[] values = {LogicalValue.TRUE, LogicalValue.FALSE, LogicalValue.UNKNOWN};
        LogicalValue[][] and = {{values[0], values[1], values[2]}, {values[1], values[1], values[1]},
                {values[2], values[1], values[2]}};
        LogicalValue[][] or = {{values[0], values[0], values[0]}, {values[0], values[1], values[2]},
                {values[0], values[2], values[2]}};
        for (int i = 0; i < 3; i++) for (int j = 0; j < 3; j++) {
            assertEquals(and[i][j], values[i].and(values[j]));
            assertEquals(or[i][j], values[i].or(values[j]));
        }
        assertEquals(LogicalValue.UNKNOWN, LogicalValue.UNKNOWN.or(LogicalValue.UNKNOWN.not()));
    }

    @Test void exactUnicodeIsPreservedWithoutNormalizationAndMalformedUtf16IsRejected() {
        assertNotEquals(profile("é").identity(), profile("e\u0301").identity());
        assertThrows(IllegalArgumentException.class, () -> profile("\ud800"));
        assertEquals("{\"𐀀\":1,\"\":2}", CanonicalJson.write(Map.of("\ue000", 2, "\ud800\udc00", 1)));
        assertNotEquals(FiniteDomain.Value.exact(""), FiniteDomain.Value.missing());
        assertNotEquals(FiniteDomain.Value.exact(" false "), FiniteDomain.Value.exact("false"));
        // Independent literal R0 envelope, hashed with .NET SHA256; not generated by the Java identity helper.
        assertEquals("spring-condition-expression:sha256:ab8ca42dbe50b73dc4f540f9fdd2e5630c2490ee9b486bbf380259ee7bc07271", profile("a").identity().value());
    }

    @Test void expressionsCannotMixFrameworkPinsOrSmuggleOperandsIntoOtherOperators() {
        var other = ConditionExpression.atom(new ConditionExpression.Semantics(
                SEMANTICS.version(), ContentDigest.sha256Utf8("different-pin")), new ConditionExpression.Profile("a"));
        assertThrows(IllegalArgumentException.class, () -> ConditionExpression.all(SEMANTICS, List.of(profile("a"), other)));
        assertEquals(Set.of(ConditionExpression.Dependency.CONFIGURATION), profile("a").dependencies());
        assertEquals(1, profile("a").depth());
        assertEquals(2, ConditionExpression.not(profile("a")).depth());
    }

    @Test void acceptedR0KleeneFixtureRowsAndAlgebraicLawsHold() throws Exception {
        try (var stream = getClass().getResourceAsStream("/fixtures/m4b1/r0-kleene.tsv")) {
            assertNotNull(stream);
            var lines = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8).lines().skip(1).toList();
            assertEquals(21, lines.size());
            for (String line : lines) {
                String[] row = line.split("\t");
                LogicalValue left = truth(row[2]);
                LogicalValue result = switch (row[1]) {
                    case "all" -> left.and(truth(row[3])); case "any" -> left.or(truth(row[3]));
                    case "not" -> left.not(); default -> throw new AssertionError("Unregistered fixture operator");
                };
                assertEquals(truth(row[4]), result, row[0]);
            }
        }
        for (LogicalValue a : LogicalValue.values()) for (LogicalValue b : LogicalValue.values()) {
            assertEquals(a, a.not().not());
            assertEquals(a.and(b).not(), a.not().or(b.not()));
            assertEquals(a.or(b).not(), a.not().and(b.not()));
            for (LogicalValue c : LogicalValue.values()) {
                assertEquals(a.and(b).and(c), a.and(b.and(c)));
                assertEquals(a.or(b).or(c), a.or(b.or(c)));
                assertEquals(a.and(b.or(c)), a.and(b).or(a.and(c)));
            }
        }
    }
    private static LogicalValue truth(String value) {
        return switch (value) { case "T" -> LogicalValue.TRUE; case "F" -> LogicalValue.FALSE; case "U" -> LogicalValue.UNKNOWN;
            default -> throw new AssertionError("Unregistered logical value"); };
    }
}
